# example mail config (lives in /var/www/citysdk/shared/config)
# used by cms and periodicals
---
:address: zimbra.waag.org
:port: '587'
:enable_starttls_auto: true
:user_name: <user>
:password: <pwd>
:authentication: :plain
:domain: waag.org
